### ISSUE TITLE
mm10 sequence assembly for repeat enrichment estimator

### ISSUE THREAD

**Issue by vdumeaux** [parklab/Software-Issues#14]
Please provide us with the following information so we can help you out:

#### The Software:

Repeat enrichment estimator

#### The Problem:

I have tried to create the sequence assembly file for mm10 following the instructions in the readme file of the source code but it does not seem that the canonical repeat sequence concatenate with instance sequences identified by the default RepeatMasker scan.

#### Details:

here is the head of mm10.combined.fa that I obtain
>HY5
agttggtccgagtgttgtgggttattgttaagttgatttaacattgtctccccccacaaccgcgcttgactagcttgctgttttNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
>tRNA-Gln-CAG
ggttccatggtgtaatggtaagcactctggactctgaatccagcgatccgagttcaagtctcggtggaacctccaNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

message:
reading repbase /home/data/tools/RepeatMasker/Libraries/RepeatMaskerLib.embl ... done (45184 repeats).
reading repeatmasker file mm10.fa.out.gz ... done (18538 repeat types).
matching canonical names ... done (matched 1279 repeat types out of 18538).
organism-matched repeats: [Lx6_3end Lx9_3end Lx8b_3end Lx11_3end Lx7_3end Lx8_3end L1_Rod2_orf2 7SLRNA_short_ MERVL_2A Lx10_3end RodERV21]
initializing genome sequence database ... done ids=[chr10 chr12 chr14 chr16 chr18 chr1_GL456210_random chr1_GL456212_random chr1_GL456221_random chr1 chr3 chr4_GL456350_random chr4_JH584292_random chr4_JH584294_random chr5_JH584297_random chr5_JH584299_random chr5 chr7 chr9 chrM chrUn_GL456359 chrUn_GL456360 chrUn_GL456366 chrUn_GL456368 chrUn_GL456379 chrUn_GL456382 chrUn_GL456393 chrX_GL456233_random chrY_JH584301_random chrY_JH584303_random chrY chr11 chr13 chr15 chr17 chr19 chr1_GL456211_random chr1_GL456213_random chr2 chr4_GL456216_random chr4_JH584293_random chr4_JH584295_random chr4 chr5_GL456354_random chr5_JH584296_random chr5_JH584298_random chr6 chr7_GL456219_random chr8 chrUn_GL456239 chrUn_GL456367 chrUn_GL456370 chrUn_GL456372 chrUn_GL456378 chrUn_GL456381 chrUn_GL456383 chrUn_GL456385 chrUn_GL456387 chrUn_GL456389 chrUn_GL456390 chrUn_GL456392 chrUn_GL456394 chrUn_GL456396 chrUn_JH584304 chrX chrY_JH584300_random chrY_JH584302_random]
(CGAGG)n ... 0 valid out of 4 specified sequences (0)
RMER19B ... 0 valid out of 5497 specified sequences (0)
PB1D7 ... 0 valid out of 24234 specified sequences (0)
L2-1_Crp ... 0 valid out of 2 specified sequences (0)
MER70A ... 0 valid out of 184 specified sequences (0)
RLTR15 ... 0 valid out of 2419 specified sequences (0)
MARE6 ... 0 valid out of 45 specified sequences (0)
(GAAAA)n ... 0 valid out of 369 specified sequences (0)
(GAA)n ... 0 valid out of 1428 specified sequences (0)
LTR33A_ ... 0 valid out of 459 specified sequences (0)
Eulor9C ... 0 valid out of 70 specified sequences (0)
(CAAT)n ... 0 valid out of 377 specified sequences (0)

Thank you,

Vanessa

**Comment by scottx611x** [comment]
Ping @pkharchenko

**Comment by pkharchenko** [comment]
@vdumeaux Looks like it's not able to find any instances ... Please check to make sure that the RepeatMasker files were generated for the same assembly, and that the chromosome naming is consistent (i.e. "chr1" vs. just "1", etc.)

**Comment by vdumeaux** [comment]
Hi @pkharchenko, I checked the files

- repeatMasker file mm10.fa.out - the regions match the mm10 UCSC repeatmasker track so ok

- my repeatMaskerLib.embl is updated (Sources: Dfam_Consensus RELEASE 20170127;                RepBase RELEASE 20170127) and I specified Species to mouse

- my genome fasta files are from mm10 UCSC (with chr1 naming) downloaded from http://hgdownload.cse.ucsc.edu/goldenPath/mm10/chromosomes/

it seems all ok to me but maybe I am missing something - is it possible that the UCSC fasta files do not contain the info I need? Do you plan to release the assembly for mm10?

Thank you in advance for the help. best,

Vanessa

**Comment by pkharchenko** [comment]
Hi Vanessa,
 Here’s advice from a postdoc in Alice Lee’s lab who has made an mm10 repeat assembly:

> recommend using mm10 genome fasta files from http://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/ <https://urldefense.proofpoint.com/v2/url?u=http-3A__hgdownload.soe.ucsc.edu_goldenPath_mm10_bigZips_&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=gseIQeAp1iKV5FBIGilNBoXjxAxlVfcPcK3DX-BY6QQ&m=YeM0n3gEr1zLfPH2ppOINDUwj-Bne5OUTCdPZhuxvvk&s=Udebp2gOCMwEJuIHmQYqEA-LedAMU63THRVyWAFH6Zw&e=>
> If you download mm10.2bit, and convert it to fa format, then you will get a whole chromosome genome file.
> The genome file "with chr1 naming" might caused the problem. 


-peter.

**Comment by vdumeaux** [comment]
Hi Peter,

Thanks for looking into this. I followed your suggestion and used one fasta file that was from the conversion of the .2bit UCSC file but it did not solve the problem. 

I looked into my perl version (that was pretty old, 5.8) so I decided to install a local version of the newest perl release (5.26.1). That did not solve the problem neither (the output is the same) but now I have an error message:
"Possible precedence issue with control flow operator at /home/data/tools/perl/perl-5.26.1/lib/perl5/Bio/DB/IndexedBase.pm line 845."
Could it be due to Bioperl ? which perl and bioperl versions would you recommend?

Thank you

**Comment by scottx611x** [comment]
@vdumeaux I'm going to close this for now. If the issue hasn't been resolved yet please feel free to reopen
