### ISSUE TITLE
Noisy CNV profile with many focal events

### ISSUE THREAD

**Issue by Rashesh7** [parklab/Software-Issues#16]
Hello,
I am currently benchmarking bicseq2 version 0.2.4 for incorporating in our pipeline. We have been using nbicseq v0.7a in our pipeline.
While testing I ran multiple iterations of bicseq2 on the same samples, to determine the reproducibility of the CNV calls. I noticed that probably 1 out of 10 iterations had noisy focal events being called. 

I increased the subsampling fraction of the reads to 0.001. I saw the similar issue. These samples have a single read length(151 bp). Coverage is 50X normal 90X tumor. 
I am attaching the CNV plots for the same.

1. Have you seen this issue before? If yes then, what would you suggest as the solution?
2. Is there a way to increase the reproducibility from iteration to iteration?

Your support and suggestions are appreciated. 

Thank you,
Rashesh
<img width="1497" alt="bicseq2_iterations" src="https://user-images.githubusercontent.com/4691098/43270478-24bae430-90c3-11e8-894d-c4e152f66abf.png">

**Comment by scottx611x** [comment]
@Rashesh7 I'm not able to help with this particular request, but I'll try to find someone in our lab that can help you out!

**Comment by sanaviat** [comment]
@Rashesh7 I just shared the issue that you pointed out with Ruibin Xi, who is the author of the package. I'll let you know soon.

**Comment by sanaviat** [comment]
@Rashesh7 Hi. Could you try v0.2.6? http://www.math.pku.edu.cn/teachers/xirb/downloads/software/BICseq2/BICseq2/BICseq2-norm_v0.2.6.tar.gz

**Comment by Rashesh7** [comment]
Hi @sanaviat,
Do you have a log of what is updated in this version compared to v0.2.4?

Thank you.

**Comment by sanaviat** [comment]
@Rashesh7 Sorry but there is not a log file but the main update in this version is to set a fixed seed for random sampling in the normalization.

**Comment by Rashesh7** [comment]
Hi @sanaviat 
I am currently running a test using v0.2.6. 
I had another query. Do you have mappability files available for GRCH38?

**Comment by Rashesh7** [comment]
@sanaviat , using v0.2.6. solved the issue with the difference between iterations. 

Thank you.

**Comment by sanaviat** [comment]
@Rashesh7 Great. Sorry I did not reply at your last question. I always used GRCH37.

**Comment by scottx611x** [comment]
@Rashesh7 @sanaviat I'm going to mark this as resolved! Feel free to reopen if anything else comes up! 😄
