### ISSUE TITLE
Noisy CNV profile with many focal events

### ISSUE THREAD

**Issue by scottx611x** [parklab/Software-Issues#17]
Submitter: Rashesh Sanghvi
Email: rsanghvi@nygenome.org
Hello,
I am currently benchmarking bicseq2 version 0.2.4 for incorporating in our pipeline. We have been using nbicseq v0.7a in our pipeline. 
While testing I ran multiple iterations of bicseq2 on the same samples, to determine the reproducibility of the CNV calls. I noticed that probably 1 out of 10 iterations had noisy focal events being called. 
I increased the subsampling fraction of the reads to 0.001. I saw the same issue. These samples have a single read length(151 bp). Coverage is 50X normal 90X tumor. 
I am attaching the CNV plots for the same.

1) Have you seen this issue before? If yes then, what would you suggest as the solution? 
2) Is there a way to increase the reproducibility from iteration to iteration?

Your support and suggestions are appreciated. 

Thank you,
Rashesh

**Comment by Rashesh7** [comment]
This is a duplicate issue. I already submitted it on github issues. Sorry about that.
