### ISSUE TITLE
Meerkat Installation compiling issue

### ISSUE THREAD

**Issue by sckinta** [parklab/Software-Issues#19]
#### The Software:

Meerkat

#### The Problem:

I have a software compiling issue while installing src packages for Meerkat. After compling mybamtools successfully, I failed to compile another three binary files (bamreader, dre and sclus) based on pre-build mybamtools.

#### Details:
I have change BTROOT to the bamtools path  (/mnt/isilon/sfgi/programs/Meerkat/src/mybamtools), and add -lz to first compiling step
`$(CXX) -L $(BTLIB) $(PROFILE) -o bamreader Histogram.o ReadGroup.o bamreader.o gzstream.o -lbamtools -lbamtools-utils -lz`

The error seems a lib linkage issue. 

> g++ -L /mnt/isilon/sfgi/programs/Meerkat/src/mybamtools/lib  -o bamreader Histogram.o ReadGroup.o bamreader.o gzstream.o -lbamtools -lbamtools-utils -lz
> ReadGroup.o:ReadGroup.cpp:function std::ReadGroup::~ReadGroup(): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
> ReadGroup.o:ReadGroup.cpp:function std::ReadGroup::~ReadGroup(): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
> ReadGroup.o:ReadGroup.cpp:function std::ReadGroup::~ReadGroup(): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
> ReadGroup.o:ReadGroup.cpp:function std::ReadGroup::~ReadGroup(): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
> ReadGroup.o:ReadGroup.cpp:function clipAlignment(BamTools::BamAlignment&): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
> ReadGroup.o:ReadGroup.cpp:function clipAlignment(BamTools::BamAlignment&): error: undefined reference to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'

I tried to use three different versions of GCC to compile (`GCC/4.8.2`, `GCC/4.9.2`, `GCC/6.3.0-2.27`). None of them worked. Could you please help?

**Comment by simoncchu** [comment]
Would you please show the boost version?

**Comment by sckinta** [comment]
> Would you please show the boost version?

the boost version is 1.53
