### ISSUE TITLE
Meerkat Empty Output Files

### ISSUE THREAD

**Issue by scottx611x** [parklab/Software-Issues#5]
Email: mark.youngblood@yale.edu
Submitter: Mark Youngblood
Hi,

I am trying to install Meerkat for use with Illumina WGS data. I downloaded the software and example data from this website: http://compbio.med.harvard.edu/Meerkat/. To test the installation, I have been trying to process the example dataset, however my final output files appear to be empty (example.intra.refined.typ.sorted; example.inter.refined.typ.sorted; example.variants). I have confirmed that I am using the correct software versions specified in the manual. The only abnormality I see when running Meerkat is that I receive an R error during the preprocessing step related to a missing file "Rscript execution error: No such file or directory". Digging into the code, it seems to be looking for a file "example.insert.r" that I think is supposed to be created by Bamreader? However, when I run Bamreader by itself, I do not see this file as a part of the log output (example.pre.log). I am not sure if this error is what is causing the final output files to be empty, but it is the only abnormality when I run the three steps. The first two steps take about 10 minutes to execute, but the final step (mechanism) executes instantly. I do not see any errors in example.dre.log or bwa.err.

I would really appreciate any help you are able to provide. I can send any log files that are needed. Thanks so much for your help and for publishing this tool,

**Comment by Reedwarbler** [comment]
Hi Mark,

Would you please post out (or attach) the "example.pre.log" file? 

Simon

**Comment by mark32309** [comment]
Hi, thank you for your fast response! The file is attached,

-Mark
[example.pre.log.txt](https://github.com/parklab/Software-Issues/files/1174255/example.pre.log.txt)

**Comment by simoncchu** [comment]
@mark32309  It seems no error happens in the "preprocessing" step. Is there a "xxxx.dre.log" file generated?

**Comment by mark32309** [comment]
Yes, here it is
[example.dre.log.txt](https://github.com/parklab/Software-Issues/files/1174632/example.dre.log.txt)

**Comment by mark32309** [comment]
@Reedwarbler Hi, I wanted to see if you had any ideas from the dre.log file? Thanks again for your help,

**Comment by simoncchu** [comment]
@mark32309 
Cannot find error from the two log files. And the error is not repeated when I test on a server. 

@msherman997 do you have any idea of the possible reason cause the error?

**Comment by maxwellsh** [comment]
Hi Mark, thanks for reaching out on the issue. "example.insert.r" should be automatically created, executed, and then deleted during the preprocessing step in order to calculate insert size statistics. My guess is that this has something to do with the way that R is installed / configured on your system. Can you please provide the following additional information:

the output of "which R" (or how R is specified in your $PATH variable)
Are you able to run ./bin/bamreader from command?
The output of "ls -l" for run folder.
isinfo file if it's generated.
The error message and at what point it is thrown.

**Comment by mark32309** [comment]
@msherman997 @Reedwarbler Hi msherman997, I tried with a different version of R and the problem is resolved! Thanks so much for your help, -Mark

**Comment by simoncchu** [comment]
Thank you @msherman997 ! You are more experienced!
